apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkon-deployment1
  labels:
    app: thinkon-deployment1
spec:
  selector:
    matchLabels:
      app: thinkon-deployment1
  template:
    metadata:
      labels:
        app: thinkon-deployment1
    spec:
      containers:
      - name: mysql-db
        image: mysql:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

  
