apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkon-deployment1
  labels:
    environment: test
spec:
  selector:
    matchLabels:
      environment: test
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavilable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - name: mysql-db
        image: mysql:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

  
