apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkon-deployment2
  labels:
    app: thinkon-deployment2
spec:
  selector:
    matchLabels:
      app: thinkon-deployment2
  template:
    metadata:
      labels:
        app: thinkon-deployment2
    hostNetwork: true
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
          name: nginx-port
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: thinkon-service
spec:
  selector:
      app: nginx
  ports:
    - name: nginx-port
      port: 80
  
